export const mockedData = [
  {
    firstName: "Lucas",
    lastName: "Smith",
    dateOfBirth: "11/14/2001",
    startDate: "03/14/2013",
    street: "105 KROME AVE",
    city: "Montgomery",
    state: "AL",
    zipCode: "35004",
    department: "Human Resources",
  },
  {
    firstName: "Matthew",
    lastName: "Johnson",
    dateOfBirth: "10/14/1987",
    startDate: "02/06/2021",
    street: "205 MAGIC AVE",
    city: "Juneau",
    state: "AK",
    zipCode: "99950",
    department: "Marketing",
  },
  {
    firstName: "James",
    lastName: "Williams",
    dateOfBirth: "10/01/1980",
    startDate: "07/02/2010",
    street: "45 DONALD ST",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85001",
    department: "Legal",
  },
  {
    firstName: "Patricia",
    lastName: "Brown",
    dateOfBirth: "02/14/1994",
    startDate: "18/04/2008",
    street: "95 YESMAN ST",
    city: "Litte Rock",
    state: "AR",
    zipCode: "71601",
    department: "Engineering",
  },
  {
    firstName: "Jennifer",
    lastName: "Jones",
    dateOfBirth: "10/21/1993",
    startDate: "12/01/2004",
    street: "42 SUNNY BLVD",
    city: "Sacramento",
    state: "CA",
    zipCode: "96162",
    department: "Human Resources",
  },
  {
    firstName: "William",
    lastName: "Garcia",
    dateOfBirth: "07/03/1976",
    startDate: "06/25/2015",
    street: "05 ANDERSON BLVD",
    city: "Denver",
    state: "CO",
    zipCode: "80001",
    department: "Sales",
  },
  {
    firstName: "Thomas",
    lastName: "Miller",
    dateOfBirth: "06/01/2002",
    startDate: "11/25/1981",
    street: "42 APPLE PARK ST",
    city: "Hartford",
    state: "CT",
    zipCode: "06001",
    department: "Marketing",
  },

  {
    firstName: "Nancy",
    lastName: "Davis",
    dateOfBirth: "04/29/1999",
    startDate: "04/08/2004",
    street: "548 BOWSER PL",
    city: "Dover",
    state: "DE",
    zipCode: "19701",
    department: "Legal",
  },
  {
    firstName: "Anthony",
    lastName: "Rodriguez",
    dateOfBirth: "05/17/1991",
    startDate: "08/02/2021",
    street: "23 SMITH DR",
    city: "Florida",
    state: "FL",
    zipCode: "32003",
    department: "Human Resources",
  },
  {
    firstName: "Sandra",
    lastName: "Martinez",
    dateOfBirth: "01/01/2000",
    startDate: "06/03/2019",
    street: "18 MUG PL",
    city: "Atlanta",
    state: "GA",
    zipCode: "39901",
    department: "Engineering",
  },
  {
    firstName: "Andrew",
    lastName: "Taylor",
    dateOfBirth: "09/23/2003",
    startDate: "10/01/2021",
    street: "50 ARIGATO BLVD",
    city: "Honolulu",
    state: "HI",
    zipCode: "96898",
    department: "Sales",
  },
  {
    firstName: "Edward",
    lastName: "Moore",
    dateOfBirth: "12/24/1980",
    startDate: "13/07/2022",
    street: "91 ALBERT ST",
    city: "Boise",
    state: "ID",
    zipCode: "83201",
    department: "Marketing",
  },
  {
    firstName: "Cynthia",
    lastName: "Jackson",
    dateOfBirth: "02/11/1979",
    startDate: "12/04/2021",
    street: "39 HAMER PL",
    city: "Springfield",
    state: "IL",
    zipCode: "60001",
    department: "Human Resources",
  },
  {
    firstName: "Laura",
    lastName: "White",
    dateOfBirth: "10/24/1980",
    startDate: "08/26/2019",
    street: "4 OPENCLASSROOMS ST",
    city: "Indianapolis",
    state: "IN",
    zipCode: "46001",
    department: "Sales",
  },
  {
    firstName: "Jonathan",
    lastName: "Harris",
    dateOfBirth: "01/21/1987",
    startDate: "05/02/2011",
    street: "306 CITROEN PL",
    city: "Des Moines",
    state: "IA",
    zipCode: "50001",
    department: "Legal",
  },
  {
    firstName: "Scott",
    lastName: "Lewis",
    dateOfBirth: "02/07/1995",
    startDate: "08/23/2012",
    street: "178 CLINTON DR",
    city: "Topeka",
    state: "KS",
    zipCode: "67954",
    department: "Marketing",
  },
  {
    firstName: "Larry",
    lastName: "Clark",
    dateOfBirth: "03/26/1996",
    startDate: "26/02/2014",
    street: "654 OBAMA ST",
    city: "Frankfort",
    state: "KY",
    zipCode: "42788",
    department: "Human Resources",
  },
  {
    firstName: "Katherine",
    lastName: "Robinson",
    dateOfBirth: "10/20/1971",
    startDate: "11/05/2016",
    street: "756 EINSTEIN BLVD",
    city: "Baton Rouge",
    state: "LA",
    zipCode: "71497",
    department: "Engineering",
  },
  {
    firstName: "Julie",
    lastName: "Young",
    dateOfBirth: "07/08/1988",
    startDate: "09/03/2019",
    street: "44 JACKSON ST",
    city: "Augusta",
    state: "ME",
    zipCode: "03901",
    department: "Sales",
  },
  {
    firstName: "Joyce",
    lastName: "Hill",
    dateOfBirth: "07/23/1997",
    startDate: "11/11/2011",
    street: "496 NETFLIX PL",
    city: "Annapolis",
    state: "MD",
    zipCode: "20588",
    department: "Human Resources",
  },
  {
    firstName: "Peter",
    lastName: "Nelson",
    dateOfBirth: "12/03/2000",
    startDate: "07/07/2015",
    street: "945 ENDWORLD ST",
    city: "Boston",
    state: "MA",
    zipCode: "05544",
    department: "Marketing",
  },
  {
    firstName: "Jeremy",
    lastName: "Green",
    dateOfBirth: "02/24/1990",
    startDate: "01/05/2014",
    street: "72 LUCKY ST",
    city: "Lansing",
    state: "MI",
    zipCode: "49971",
    department: "Legal",
  },
  {
    firstName: "Arthur",
    lastName: "Carter",
    dateOfBirth: "05/14/1987",
    startDate: "12/29/2008",
    street: "374 LIFE ST",
    city: "Saint Paul",
    state: "MN",
    zipCode: "55001",
    department: "Engineering",
  },
  {
    firstName: "Sophia",
    lastName: "Adams",
    dateOfBirth: "01/06/1992",
    startDate: "08/06/2019",
    street: "860 AMERICAN DR",
    city: "Jackson",
    state: "MS",
    zipCode: "39776",
    department: "Sales",
  },
  {
    firstName: "Janice",
    lastName: "Lee",
    dateOfBirth: "05/28/1974",
    startDate: "09/15/2018",
    street: "765 HELP BLVD",
    city: "Jefferson City",
    state: "MO",
    zipCode: "63001",
    department: "Legal",
  },
  {
    firstName: "Joe",
    lastName: "Sanchez",
    dateOfBirth: "10/13/1980",
    startDate: "04/09/2008",
    street: "351 MSI PL",
    city: "Helena",
    state: "MT",
    zipCode: "59937",
    department: "Marketing",
  },
  {
    firstName: "Samantha",
    lastName: "Gonzalez",
    dateOfBirth: "03/20/1998",
    startDate: "03/10/2015",
    street: "25 WHITE DR",
    city: "Lincoln",
    state: "NE",
    zipCode: "68001",
    department: "Human Resources",
  },
  {
    firstName: "Andrew",
    lastName: "Martin",
    dateOfBirth: "30/07/1990",
    startDate: "07/01/2011",
    street: "599 NW BAY BLVD",
    city: "Carson City",
    state: "NV",
    zipCode: "88901",
    department: "Engineering",
  },
  {
    firstName: "Barbara",
    lastName: "Campbell",
    dateOfBirth: "01/15/1987",
    startDate: "12/04/2009",
    street: "8 ARLINGTON DR",
    city: "Concord",
    state: "NH",
    zipCode: "03897",
    department: "Sales",
  },
  {
    firstName: "Christine",
    lastName: "Yokanze",
    dateOfBirth: "12/22/1965",
    startDate: "08/04/2007",
    street: "106 DOYERS ST",
    city: "Trenton",
    state: "NJ",
    zipCode: "08989",
    department: "Human Resources",
  },
];
